# First Steps with PyTorch

[Cillian](https://cjber.github.io) suggested I check out [Aakash N.S.](https://www.linkedin.com/in/aakashns/?originalSubdomain=in)'s new PyTorch course. Which I did, and it looks great -- as does his [Jovian.ml platform for sharing Jupyter notebooks](https://jovian.ml). 

The course is spread over six weeks, with weekly assignments. The first is to explore five functions from PyTorch's `.Tensor` class. So [here we go](https://www.youtube.com/watch?v=M0qSjLDVElY)!

Let's start by importing the `torch` library and instantiating a `Tensor` object.

In [1]:
import torch

In [2]:
t = torch.Tensor()

## 1. GPU Computing with `.cuda()`

One of the cool things about PyTorch is that it's set up for superfast GPU computing using NVIDIA's CUDA interface. The computer I have for my PhD research is CUDA enabled, but I haven't really had opportunity to make use of this fact yet. Let's check if CUDA is available on this machine...

In [3]:
torch.cuda.is_available()

True

By default, PyTorch just uses your CPU -- if you want it to use your GPU as its computing `device`, you need to say so explicitly.

In [4]:
t.device

device(type='cpu')

In [5]:
if torch.cuda.is_available():
    t = t.cuda()

## 2. Making New Tensors with `.new_tensor()`

If you haven't heard of *tensors* before, you've probably still heard of *vectors* and *matrices*.

In [6]:
vector = t.new_tensor([1,2])
vector

tensor([1., 2.], device='cuda:0')

In [7]:
matrix = t.new_tensor([
    [1,2],
    [2,1]
])
matrix

tensor([[1., 2.],
        [2., 1.]], device='cuda:0')

A tensor is their generalization: a vector is tensor of *rank* (or dimensionality) 1; a matrix is a rank-2 tensor; and you can go on.

In [8]:
print(f'The rank of a vector is {vector.dim()}')
print(f'The rank of a matrix is {matrix.dim()}')

The rank of a vector is 1
The rank of a matrix is 2


And what we think of as 'ordinary numbers' are tensors of rank zero.

In [9]:
scalar = t.new_tensor(3)
print(scalar)
print(f'The rank of a scalar is {scalar.dim()}')

tensor(3., device='cuda:0')
The rank of a scalar is 0


PyTorch also allows us to quickly generate a new tensor that is full of zeros, ones, or whatever number we like.

In [10]:
zeros = t.new_zeros((10,10))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], device='cuda:0')

In [11]:
ones = t.new_ones((5,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

In [12]:
anything = t.new_full((8,5),17)
anything

tensor([[17., 17., 17., 17., 17.],
        [17., 17., 17., 17., 17.],
        [17., 17., 17., 17., 17.],
        [17., 17., 17., 17., 17.],
        [17., 17., 17., 17., 17.],
        [17., 17., 17., 17., 17.],
        [17., 17., 17., 17., 17.],
        [17., 17., 17., 17., 17.]], device='cuda:0')

Or we can generate a random array of whatever shape:

In [13]:
random = torch.rand(3,3)
random

tensor([[0.4485, 0.1529, 0.7111],
        [0.3065, 0.3602, 0.1230],
        [0.9874, 0.7289, 0.0033]])

## 3. Matrix Multiplicatoin with `.matmul()`

PyTorch lets us do matrix multiplication with `.matmul()`

In [14]:
matrix.matmul(matrix)

tensor([[5., 4.],
        [4., 5.]], device='cuda:0')

In [15]:
matrix.matmul(vector)

tensor([5., 4.], device='cuda:0')

However, this doesn't work quite how I expected -- PyTorch will transpose a one-dimensional vector as necessary to give a dot product (ie. an inner product).

In [16]:
vector.matmul(vector.T) 

tensor(5., device='cuda:0')

In [17]:
vector.matmul(vector)

tensor(5., device='cuda:0')

In [18]:
vector.T.matmul(vector)

tensor(5., device='cuda:0')

In [19]:
vector.T.matmul(vector.T)

tensor(5., device='cuda:0')

If you do want the outer product, you can use `.ger()`.

In [20]:
vector.ger(vector)

tensor([[1., 2.],
        [2., 4.]], device='cuda:0')

## 4. Finding the Inverse with `.inverse()`

PyTorch makes it trivial to get the inverse of a tensor:

In [21]:
matrix.inverse()

tensor([[-0.3333,  0.6667],
        [ 0.6667, -0.3333]], device='cuda:0')

We can check whether this inverse does actually work:

In [22]:
matrix @ matrix.inverse()

tensor([[1., 0.],
        [0., 1.]], device='cuda:0')

## 5. Easy Eigenvalues with `.eig()`

And it's similarly easy to find a tensor's eigenvalues:

In [23]:
matrix.eig()

torch.return_types.eig(
eigenvalues=tensor([[ 3.0000,  0.0000],
        [-1.0000,  0.0000]], device='cuda:0'),
eigenvectors=tensor([], device='cuda:0'))

If you also want the eigenvectors, then just say so when you run the function.

In [24]:
matrix.eig(True)

torch.return_types.eig(
eigenvalues=tensor([[ 3.0000,  0.0000],
        [-1.0000,  0.0000]], device='cuda:0'),
eigenvectors=tensor([[ 0.7071, -0.7071],
        [ 0.7071,  0.7071]], device='cuda:0'))

## Comparing PyTorch with GPU to Numpy

Now we can use those simple functions to generate a big tensor and see how quickly PyTorch can find its eigenvalues compared to Numpy.

In [25]:
dim_x = 10**3
dim_y = 10**3

In [26]:
import numpy as np

In [27]:
massive = torch.randn((dim_x,dim_y)).cuda()
massive

tensor([[-0.0745,  0.2748, -1.4848,  ..., -0.9740,  0.6911,  0.8833],
        [ 0.5165, -0.3985,  0.7268,  ...,  2.3921, -0.5628,  0.1531],
        [-0.3024,  1.2555, -1.5737,  ..., -0.9724, -1.0857, -1.1055],
        ...,
        [ 1.8176, -0.3609, -0.8389,  ..., -0.7773, -2.0532,  0.6860],
        [ 0.6077, -1.1111, -0.0602,  ..., -0.1695, -0.2805,  1.6845],
        [ 0.2828,  0.4366, -1.0544,  ...,  0.2385,  0.4885, -1.2533]],
       device='cuda:0')

In [28]:
numpy_version = massive.cpu().numpy()
numpy_version

array([[-0.0744525 ,  0.27476978, -1.4848366 , ..., -0.9740233 ,
         0.69107497,  0.88326013],
       [ 0.5165413 , -0.39849052,  0.7268396 , ...,  2.392065  ,
        -0.56276095,  0.15305625],
       [-0.30239376,  1.255493  , -1.5737166 , ..., -0.97236514,
        -1.0857061 , -1.1054957 ],
       ...,
       [ 1.8176234 , -0.3608592 , -0.83891994, ..., -0.7772828 ,
        -2.0532408 ,  0.68600905],
       [ 0.6076961 , -1.111058  , -0.06023345, ..., -0.16951588,
        -0.28046852,  1.6844993 ],
       [ 0.2827644 ,  0.43656364, -1.054425  , ...,  0.23848584,
         0.48854375, -1.2532959 ]], dtype=float32)

We'll use Jupyter's `%time` magic...

In [29]:
%time
pytorch_eigs = massive.eig()

CPU times: user 3 µs, sys: 2 µs, total: 5 µs
Wall time: 14.8 µs


In [30]:
%time
numpy_eigs = np.linalg.eig(numpy_version)


CPU times: user 45 µs, sys: 14 µs, total: 59 µs
Wall time: 10 µs


## Use `jovian.commit()` to share this notebook.

Well, I've left this until the last minute, and the deadline for this assignment approaches, so I should finish.

As our final step, we'll import the `jovian` library and commit this, so that the world can see it as [Jovian.ml](https://jovian.ml).

In [31]:
import jovian
jovian.commit()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "peterprescott/pytorch-first-steps" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/peterprescott/pytorch-first-steps


'https://jovian.ai/peterprescott/pytorch-first-steps'

In [32]:
jovian.submit(assignment='zerotogans-a1')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "peterprescott/pytorch-first-steps" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/peterprescott/pytorch-first-steps
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor
